### ISSUE TITLE
Panel 'panel-body' wrap code missing

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-helpers#34]
The ```\kartik\helpers\Html::panel()``` method phpdoc [implies](https://github.com/kartik-v/yii2-helpers/blob/8bd447a549793e945da131ed6a73ffeec027760b/Html.php#L352) the 'body' option will be wrapped with a ```<div class="panel-body">...</div>``` yet there does not seem to be any code performing this.
Is this on purpose as the panel-body wrap should certainly be optional?

**Comment by kartik-v** [comment]
Actually the `panel-body` should be optional (and the php doc will be corrected) - the `panel-body` container is not needed for other special content like media list and table.
